#+PROPERTY: header-args :exports code
#+PROPERTY: header-args :results output silent

#+EXPORT_EXCLUDE_TAGS: noexport crypt

* Emacs packages

  It seems marmalade repo is not required anymore for most packages, so I stick with melpa. Also added org repo to install org-plus-contrib.

  #+BEGIN_SRC emacs-lisp
  (require 'package)

  (setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
  (add-to-list 'package-archives '("org-contrib" . "https://elpa.nongnu.org/nongnu/") t)
  #+END_SRC

  One problem of melpa repository is that it receives updates as soon as their published, so it's up to the maintainer to keep the package stable. The upside of this is that bugs are detected and fixed early. The downside is that you may have unexpected bugs.

  AFAIK, the only way to avoid this is to use [[http://stable.melpa.org][melpa stable]]. You can then pin some packages to this repo like this:

  #+BEGIN_SRC emacs-lisp
    (add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)

    ;; (add-to-list 'package-pinned-packages '(cider . "melpa-stable") t)
    ;; (add-to-list 'package-pinned-packages '(clj-refactor . "melpa-stable") t)
  #+END_SRC

  I keep a list of the packages I've installed so that a fresh install requires just to eval =gimme-my-packages=. Make sure you re-eval it after adding a package.

  #+BEGIN_SRC emacs-lisp
    (when (memq window-system '(mac ns x))
      (exec-path-from-shell-initialize))

    (defun gimme-my-packages ()
      (interactive)

      ;; consider using package-selected-packages
      (let ((required-packages '(ace-isearch

                                 android-mode

                                 browse-kill-ring

                                 company
                                 company-tern

                                 conkeror-minor-mode

				 clojure-mode
				 clojure-snippets
				 ;; clojurescript-mode
				 clj-refactor
				 cider
				 ;; slamhound
				 4clojure

                                 company-emoji

                                 diff-hl

                                 easy-kill
                                 easy-kill-extras

                                 emmet-mode

                                 evil
				 exec-path-from-shell

                                 expand-region

                                 flycheck

                                 geben

                                 geiser

                                 ggtags

                                 gh-md

                                 gnus-alias

                                 guide-key

                                 hydra

                                 helm
                                 helm-ag
                                 helm-swoop
                                 helm-projectile

                                 json-mode

                                 js2-mode
                                 js2-refactor
                                 xref-js2
                                 indium

                                 ledger-mode

                                 logview

                                 magit
                                 orgit

                                 multiple-cursors

                                 neotree

                                 notmuch

                                 org-bullets
                                 org-mime
                                 org-download
                                 ob-http
                                 org-gcal
                                 org-jira
                                 org-beautify-theme
                                 htmlize
                                 ox-reveal
                                 orgtbl-aggregate
                                 google-contacts

                                 org-noter

                                 org-pomodoro

                                 org-tree-slide

                                 paradox

                                 paredit

                                 php-mode
                                 php-auto-yasnippets
                                 php-refactor-mode

                                 popwin

                                 projectile

                                 rainbow-delimiters

                                 restclient

                                 color-theme-sanityinc-tomorrow

                                 smart-mode-line
                                 smart-mode-line-powerline-theme

                                 smartparens

                                 smooth-scrolling

                                 solarized-theme

                                 string-edit
                                 string-inflection

                                 twittering-mode

                                 use-package

                                 vlf

                                 undo-tree

                                 web-beautify

                                 web-mode

                                 window-number
                                 )))

        (dolist (p required-packages)
          (when (not (package-installed-p p))
            (package-install p)))))
  #+END_SRC

  [[https://github.com/Malabarba/paradox/][Paradox]] is a great interface for package managing.

  #+BEGIN_SRC emacs-lisp
    (setq paradox-automatically-star t)
    (setq paradox-execute-asynchronously nil)
  #+END_SRC

  Just to be safe, backup current elpa dir when upgrading.

  #+BEGIN_SRC emacs-lisp
    (defun fvaresi/upgrade-with-bkp ()
      (interactive)

      (let* ((src (expand-file-name "elpa" user-emacs-directory))
             (bkp-name (concat "elpa.bkp." (format-time-string "%Y%m%d")))
             (dest (expand-file-name bkp-name user-emacs-directory)))
        (progn (copy-directory src dest)
               (paradox-upgrade-packages))))
  #+END_SRC

  Use John Wiegley's [[https://github.com/jwiegley/use-package][use-package]] for handling package configuration.

  #+begin_src emacs-lisp
    (eval-when-compile
      (require 'use-package))
  #+end_src
