#+PROPERTY: header-args :exports code
#+PROPERTY: header-args :results output silent

#+EXPORT_EXCLUDE_TAGS: noexport crypt

* Private							      :crypt:
-----BEGIN PGP MESSAGE-----
Version: GnuPG v1

hQEMA1NjmxQGk77XAQgAg2lDawXgH1Opi8M5pxjBTQ+FiaFxhJOo2kaNWubCdwC0
mFFRtvUL3RZjDJIL348VECrROe0kyHbBoNqBl0NNJfdKNY5cHiMGYlaUQTFrWxlv
CKsg+qbT3VJUwy0jUhf5r5XG7TeVewUitwAWzo5avqXctfwD5HyPNg/lZirIMmbc
0hpidm7kwaMtig2CM0XfFFFZK7/yQokHzQ+MN6Chi8vngfjyk0m+GbX3IdnRDdqk
AZeFD8UO5nJZTfHO7Aaxt/UJJe4XgCna3u8TZ5Vu4sj7xLrgULeL0EV6V/UhDjOA
9WS1WsRiVGg6DGvXYL7DGVh828rPmiRiPa718HMCudKpAaltNldjhl06M7ES5O4t
4j6eCkL8dzy//PH8b///DK1+HIvg09zfmUqEnCC5q6SAAQXEm396C/I+jsceVBif
HXtBWugd/lUFrXU0Vl7+3dT6YNZ9scGXUGG12QwuQTyHE8SHR9daytxQjZ/AzVuL
boyiNK6G7O6tCSY6ZVdsC5M49LNfe1gdwqEAwxN7HBSt6kLjP+1R0Hug/xW+t2+t
hv2hby3BAaK2SA==
=tcLz
-----END PGP MESSAGE-----

* Emacs packages

  It seems marmalade repo is not required anymore for most packages, so I stick with melpa. Also added org repo to install org-plus-contrib.

  #+BEGIN_SRC emacs-lisp
  (require 'package)

  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
  (add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/") t)
  #+END_SRC

  One problem of melpa repository is that it receives updates as soon as their published, so it's up to the maintainer to keep the package stable. The upside of this is that bugs are detected and fixed early. The downside is that you may have unexpected bugs.

  AFAIK, the only way to avoid this is to use [[http://stable.melpa.org][melpa stable]]. You can then pin some packages to this repo like this:

  #+BEGIN_SRC emacs-lisp
    (add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)

    ;; (add-to-list 'package-pinned-packages '(cider . "melpa-stable") t)
    ;; (add-to-list 'package-pinned-packages '(clj-refactor . "melpa-stable") t)
  #+END_SRC
  
  I keep a list of the packages I've installed so that a fresh install requires just to eval =gimme-my-packages=. Make sure you re-eval it after adding a package.

  #+BEGIN_SRC emacs-lisp
    (package-initialize)

    (defun gimme-my-packages ()
      (interactive)

      (let ((required-packages '(ace-isearch
                                 ace-jump-mode

                                 ack-and-a-half

                                 android-mode

                                 browse-kill-ring

                                 conkeror-minor-mode

                                 clojure-mode
                                 clojure-snippets
                                 clojurescript-mode
                                 clj-refactor
                                 cider
                                 company
                                 slamhound
                                 4clojure

                                 company-emoji

                                 diff-hl

                                 easy-kill
                                 easy-kill-extras

                                 emmet-mode

                                 expand-region

                                 flycheck

                                 geben

                                 gh-md

                                 gnus-alias

                                 guide-key

                                 hydra

                                 helm
                                 helm-swoop
                                 helm-projectile

                                 json-mode

                                 magit

                                 multiple-cursors

                                 neotree

                                 notmuch

                                 org-plus-contrib
  			       org-download
                                 ob-http
                                 org-gcal
                                 org-jira
                                 org-beautify-theme
                                 htmlize
                                 ox-reveal
                                 orgtbl-aggregate
                                 google-contacts

                                 paradox

                                 paredit

                                 php-mode
                                 php-auto-yasnippets
                                 php-refactor-mode

                                 popwin

                                 perspective
                                 projectile
                                 persp-projectile

                                 rainbow-delimiters

                                 restclient

                                 color-theme-sanityinc-tomorrow

                                 smart-mode-line
                                 smart-mode-line-powerline-theme

                                 smartparens

                                 smooth-scrolling

                                 solarized-theme

                                 string-edit

                                 twittering-mode

                                 undo-tree

                                 web-beautify

                                 web-mode

                                 window-number
                                 )))

        (dolist (p required-packages)
        (when (not (package-installed-p p))
            (package-install p)))))
  #+END_SRC

  [[https://github.com/Malabarba/paradox/][Paradox]] is a great interface for package managing.

  #+BEGIN_SRC emacs-lisp
    (setq paradox-automatically-star t)
    (setq paradox-execute-asynchronously nil)
  #+END_SRC

  Just to be safe, backup current elpa dir when upgrading

  #+BEGIN_SRC emacs-lisp
    (defun fvaresi/upgrade-with-bkp ()
      (interactive)

      (let* ((src (expand-file-name "elpa" user-emacs-directory))
             (bkp-name (concat "elpa.bkp." (format-time-string "%Y%m%d")))
             (dest (expand-file-name bkp-name user-emacs-directory)))
        (progn (copy-directory src dest)
               (paradox-upgrade-packages))))
  #+END_SRC

