#+PROPERTY: header-args :exports code
#+PROPERTY: header-args :results output silent

#+EXPORT_EXCLUDE_TAGS: noexport crypt

* Private							      :crypt:
-----BEGIN PGP MESSAGE-----

hQIMA2nLYyNk+9h4ARAAhIwFNIgnJWsurCMtw52S9dWqaiCk5/cuKJDSRZb9Bw+E
qBoDK80dMGAmJiopHidDd84qEhLfNDNhal32ZH9CPJWacaiHjISdiAURTePY85Sx
Hj+QFy1x/+g8oU8Wh0e2D/tn+F0+2Vy5JDtIn6vlVETAqi7lE+HASnGnRIJMUw4z
E3QEADN1F3eBpQ9vXKKWCSaFV7WDlNgpl6cdvvB5M8mIJy4jddIUs4uLVn4lPtT5
b3ihig+c4Ev4sH8ZJLnC4TP9NHGqH21cFE7TC0eg0+VOMB+YFVY+bmLqYd7u3w2E
nusyXrx/87LWXnZeeq133BLJOO1bkbj5vVAhDW0WN/OsCS7zdorsGm1aENg8s+V5
o9FKgrZ20Jy9rlph3ocxesYmHu/COqcliOu1u/QrIaHe4ue6VbIe5S5Eh9pDEIJj
kUCTvxvLi7cBzYr/DcMUy5uztaua4p3Cl2yw7xut1qbn/Z6wZQR4jIAeZVEwja/g
2fqeUlCn0qP3w//tFY3YCy2olld6NnPAIs/Vf22v0h08bDbKukAWRD35/uCFtaO9
3GNrdYXpsXNeoDaFMJWsmex+X4252WrPoh1xKFivig0cdAGEhDALIxnSR2DZj9CB
3fJK3d6rR1iK5iJt8Ed7YR5E6bOr3D8698upUgyE/eJe364jdJpsZoRxccEZ07HS
qAGmVpMfbda/e5Ao6J2UVF28SuAHbl3xW3mOZ7sLlKJnnqBqtvzrUpArriZIClZG
F5mo7MQNCHBbvE4VwaZoU4a7/WWyxKq4d1G6hFTqCf2eX+QabQx34qi9Kpkw1+TH
+EFCiCWsgb4ZMRFAP3k1puL78t1bukdyZziXxIMprOBgB5+4HWq6dhkmD9e1IGpT
jr+790UtAgi/I0ktYwJKuHl3PSBNNvCIWQ==
=3aGy
-----END PGP MESSAGE-----
* Emacs packages

  It seems marmalade repo is not required anymore for most packages, so I stick with melpa. Also added org repo to install org-plus-contrib.

  #+BEGIN_SRC emacs-lisp
  (require 'package)

  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
  (add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/") t)
  #+END_SRC

  One problem of melpa repository is that it receives updates as soon as their published, so it's up to the maintainer to keep the package stable. The upside of this is that bugs are detected and fixed early. The downside is that you may have unexpected bugs.

  AFAIK, the only way to avoid this is to use [[http://stable.melpa.org][melpa stable]]. You can then pin some packages to this repo like this:

  #+BEGIN_SRC emacs-lisp
    (add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)

    ;; (add-to-list 'package-pinned-packages '(cider . "melpa-stable") t)
    ;; (add-to-list 'package-pinned-packages '(clj-refactor . "melpa-stable") t)
  #+END_SRC
  
  I keep a list of the packages I've installed so that a fresh install requires just to eval =gimme-my-packages=. Make sure you re-eval it after adding a package.

  #+BEGIN_SRC emacs-lisp
    (package-initialize)

    (defun gimme-my-packages ()
      (interactive)

      (let ((required-packages '(ace-isearch
                                 ace-jump-mode

                                 ack-and-a-half

                                 android-mode

                                 browse-kill-ring

                                 conkeror-minor-mode

                                 clojure-mode
                                 clojure-snippets
                                 clojurescript-mode
                                 clj-refactor
                                 cider
                                 company
                                 slamhound
                                 4clojure

                                 company-emoji

                                 diff-hl

                                 easy-kill
                                 easy-kill-extras

                                 emmet-mode

  			       evil
			     
                                 expand-region

                                 flycheck

                                 geben

                                 gh-md

                                 gnus-alias

                                 guide-key

                                 hydra

                                 helm
                                 helm-swoop
                                 helm-projectile

                                 interleave

                                 json-mode

                                 magit
                                 magit-svn

                                 multiple-cursors

                                 neotree

                                 notmuch

                                 org-plus-contrib
                                 org-download
                                 ob-http
                                 org-gcal
                                 org-jira
                                 org-beautify-theme
                                 htmlize
                                 ox-reveal
                                 orgtbl-aggregate
                                 google-contacts

                                 paradox

                                 paredit

                                 php-mode
                                 php-auto-yasnippets
                                 php-refactor-mode

                                 popwin

                                 perspective
                                 projectile
                                 persp-projectile

                                 rainbow-delimiters

                                 restclient

                                 color-theme-sanityinc-tomorrow

                                 smart-mode-line
                                 smart-mode-line-powerline-theme

                                 smartparens

                                 smooth-scrolling

                                 solarized-theme

                                 string-edit

                                 twittering-mode

                                 undo-tree

                                 web-beautify

                                 web-mode

                                 window-number
                                 )))

        (dolist (p required-packages)
        (when (not (package-installed-p p))
            (package-install p)))))
  #+END_SRC

  [[https://github.com/Malabarba/paradox/][Paradox]] is a great interface for package managing.

  #+BEGIN_SRC emacs-lisp
    (setq paradox-automatically-star t)
    (setq paradox-execute-asynchronously nil)
  #+END_SRC

  Just to be safe, backup current elpa dir when upgrading

  #+BEGIN_SRC emacs-lisp
    (defun fvaresi/upgrade-with-bkp ()
      (interactive)

      (let* ((src (expand-file-name "elpa" user-emacs-directory))
             (bkp-name (concat "elpa.bkp." (format-time-string "%Y%m%d")))
             (dest (expand-file-name bkp-name user-emacs-directory)))
        (progn (copy-directory src dest)
               (paradox-upgrade-packages))))
  #+END_SRC

